from fastapi import FastAPI
from pydantic import BaseModel
from unsloth import FastLanguageModel
import torch

app = FastAPI(title="Petroleum Verification Node API")

# Configuration
MODEL_NAME = "unsloth/Llama-3.2-3B-Instruct"
LORA_PATH = "lora_verification_model"
MAX_SEQ_LENGTH = 2048

# Load model and adapters globally
print("Loading model and LoRA adapters for inference...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = MODEL_NAME,
    max_seq_length = MAX_SEQ_LENGTH,
    dtype = None,
    load_in_4bit = True,
)
# Load the trained adapters
model.load_adapter(LORA_PATH)
FastLanguageModel.for_inference(model) # Optimize for inference (2x faster)

class VerificationRequest(BaseModel):
    primary_output: str

class VerificationResponse(BaseModel):
    verification_result: str

system_prompt = """You are a senior petroleum engineer verifying operational plans and outputs generated by other AI models. 
Your job is to:
1. Verify the output for accuracy, safety, and domain rules.
2. Provide concrete corrections.
3. Do not guess; if data is missing, reject the plan and state what is missing.
4. Output your decision clearly at the end: DECISION: APPROVED, REJECTED, or MODIFIED."""

@app.post("/verify", response_model=VerificationResponse)
def verify_output(request: VerificationRequest):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Primary Model Output: '{request.primary_output}'"}
    ]
    
    # Prepare input
    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to("cuda")

    # Generate response
    outputs = model.generate(input_ids=inputs, max_new_tokens=256, use_cache=True)
    
    # Decode the output (skip the prompt)
    response_text = tokenizer.decode(outputs[0][inputs.shape[1]:], skip_special_tokens=True)
    
    return VerificationResponse(verification_result=response_text)

if __name__ == "__main__":
    import uvicorn
    # Run the server on port 8001
    uvicorn.run(app, host="0.0.0.0", port=8001)
