import requests
import json
import random

# The URL of your running Verification Node
API_URL = "http://localhost:8000/verify"

# Some synthetic random test scenarios generated by a hypothetical "Primary Model"
test_scenarios = [
    "Diagnosis: No Fault. Equipment is operating normally. Action: No maintenance required.",
    "Diagnosis: Fault Detected. The failure type is Overload. Action: Preventive maintenance is required.",
    "Diagnosis: Fault Detected. The failure type is Overheating. Action: Corrective maintenance is required.",
    "Diagnosis: No Fault. The temperature is extremely high but it is fine. Action: Ignore.",
    "Diagnosis: Fault Detected. Equipment needs to be replaced immediately because of a minor vibration."
]

def run_tests():
    print("=====================================================")
    print("🧪 KAVACH-AI VERIFICATION NODE - INTEGRATION TEST 🧪")
    print("=====================================================\n")
    
    # Pick 3 random scenarios to test
    samples = random.sample(test_scenarios, 3)
    
    for i, scenario in enumerate(samples, 1):
        print(f"--- Test Case {i} ---")
        print(f"📤 Primary Model Says: {scenario}")
        print("⏳ Sending to Verification Node (RTX 4050)...\n")
        
        try:
            # This is how you implement it in your main Kavach codebase!
            response = requests.post(
                API_URL, 
                json={"primary_output": scenario},
                timeout=30 # Wait up to 30 seconds for the model to generate text
            )
            
            if response.status_code == 200:
                result = response.json()["verification_result"]
                print(f"📥 Verification Node Reply:\n{result}\n")
            else:
                print(f"❌ API Error: {response.status_code} - {response.text}\n")
                
        except requests.exceptions.ConnectionError:
            print("❌ Connection Error: Is your inference_server.py running in another terminal?\n")

if __name__ == "__main__":
    run_tests()
